export const SCENE_COSMOS_BACKGROUND_COLOR = 0x0a0a2a;

// Lighting configuration
export const AMBIENT_LIGHT_COLOR = 0x606080;
export const AMBIENT_LIGHT_INTENSITY = 1;

export const DIRECTIONAL_LIGHT_COLOR = 0xffffff;
export const DIRECTIONAL_LIGHT_INTENSITY = 1.5;
export const DIRECTIONAL_LIGHT_POSITION = [20000, 20000, 20000];
export const DIRECTIONAL_LIGHT_SHADOW_MAP_SIZE = 2048;
export const DIRECTIONAL_LIGHT_SHADOW_BIAS = -0.001;

export const HEMISPHERE_LIGHT_SKY_COLOR = 0xffffbb;
export const HEMISPHERE_LIGHT_GROUND_COLOR = 0x080820;
export const HEMISPHERE_LIGHT_INTENSITY = 0.8; 